### ISSUE TITLE
errors markbot

### ISSUE THREAD

**Issue by guer0125** [guer0125/fancy-hover-boxes#1]
Hi there,

im getting two errors from markbot, double checked everything but not sure what's wrong

unexpected leading zero
and it says it wants `transition` under `.hover-box h2` but this is not in the instructions

thanks

@HannahDelaney

**Comment by HannahDelaney** [comment]
I'll have a look at the transition thing, but I can tell you right away that the "unexpected leading 0" error is just a way for markbot to show you best practices. It means that at the line of code it's referencing, you have something like "0.5rem" instead of ".5rem". If whatever is at that line just drops the 0 in front of the decimal, you'll get rid of that error.

I'll check out the other problem and get back to you!

**Comment by HannahDelaney** [comment]
So for the transition thing, you can actually just move the transition line that is currently applied to the class `.hover-box-caption` and move it to be under `.hover-box h2`, and it will fix the error. The `.hover-box-caption` class is not in your html so it's actually not affecting anything, and you can just remove it.

**Comment by guer0125** [comment]
that solved that,

but i still can't submit, i double checked all the css and html. not sure what wrong

**Comment by HannahDelaney** [comment]
Your screenshots are not matching. Have you tried giving your images a width and display type? We've done a pretty common ".img-flex" class a lot in the past that has the right elements. Try adding those selectors and see if you can fix it.

I've had several people with this issue, I think the lesson was built with the assumption that code would be added automatically. But it's not in there, so definitely hard to catch.

**Comment by guer0125** [comment]
thank you,
